Resources:
  WorkspaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: InstallWorkspace-MuscleApp
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: InstallUser-MuscleApp
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
